In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
data=pd.read_csv('Data Analysis Task.csv')

C:\Users\DELL\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3165: DtypeWarning: Columns (8) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [4]:
data.head()

,date,ordering_channel,mode_of_payment,bag_id,shipment_id,affiliate_bag_id,order_id,Itemcode,sku_code,ean,...,Store_City,Store_State,del_cust_name,del_cust_mobile,l1_category,l3_category,Company_Name,hsn_code,invoice_id,MRP
0,2021-04-24 22:49:19 UTC,MARKETPLACE,FY_FLIPKART_ASSURED,10299882,16194176947811624583,dbd766d8-dfe2-49d6-8dea-3808c2ff1998,FYMP6084531601CC91EE,S9C5089-040,8907181811994,NaN,...,DEHRADUN,UTTARAKHAND,Saquib Younus,9748408797,"[""Footwear""]",Flip Flops,SSIPL LIFESTYLE PRIVATE LIMITED,64041190,NaN,849.0
1,2021-08-11 20:43:46 UTC,ECOMM,ECOMM,11609617,16292033335741984031,11609617,FY6113E92A014E6066CA,927389-036,886549834401,NaN,...,MATHURA,UTTAR PRADESH,Rahul Tamaskar,9685761206,"[""Clothing""]",Activewear Joggers,SSIPL LIFESTYLE PRIVATE LIMITED,61034300,SS030/00535,2195.0
2,2021-03-09 17:31:07 UTC,MARKETPLACE,FY_FLIPKART_ASSURED,9907918,16152912668821225728,842acd6b-f3ac-4662-b92d-31d177b25b05,FYMP604763820183E9EF,S1810401-010,8907181713120,NaN,...,PUNE,MAHARASHTRA,Gaurav Kumar,8700697973,"[""Clothing""]",Activewear Joggers,SSIPL LIFESTYLE PRIVATE LIMITED,61103010,T0090/12371,1199.0
3,2021-09-29 22:57:12 UTC,MARKETPLACE,FY_FLIPKART_ASSURED,12331936,16329364323991697144,1bde7407-e1b1-41ba-9f90-bb9c1feec7ed,FYMP6154A1F00169BE96,AV5014-010,8907181795836,NaN,...,NEW DELHI,DELHI,Sandip Jena,9348036053,"[""Footwear""]",Sneakers,SSIPL LIFESTYLE PRIVATE LIMITED,64041190,NaN,1999.0
4,2021-09-29 15:30:17 UTC,MARKETPLACE,FY_AMAZON,12326311,16329096170171681635,12326311,FYMP6154393001A8F48D,FJ9217,4060512773966,NaN,...,MATHURA,UTTAR PRADESH,Amazon default customer,234242340,"[""Clothing""]",T-Shirts,SSIPL LIFESTYLE PRIVATE LIMITED,61099090,ss030/00906,999.0

In [5]:
data.shape

(46436, 42)

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46436 entries, 0 to 46435
Data columns (total 42 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   date                    46436 non-null  object
 1   ordering_channel        46436 non-null  object
 2   mode_of_payment         46436 non-null  object
 3   bag_id                  46436 non-null  int64
 4   shipment_id             46436 non-null  uint64
 5   affiliate_bag_id        46436 non-null  object
 6   order_id                46436 non-null  object
 7   Itemcode                46436 non-null  object
 8   sku_code                30083 non-null  object
 9   ean                     16353 non-null  float64
 10  upc                     0 non-null      float64
 11  item_gender             35654 non-null  object
 12  article_qnty            46436 non-null  int64
 13  ProdName                46436 non-null  object
 14  Size                    45352 non-null  object
 15  Brand                   46436 non-null  object
 16  Gender                  0 non-null      float64
 17  payment_mode            46421 non-null  object
 18  ESP                     46436 non-null  float64
 19  Amount_Paid             46436 non-null  float64
 20  unit_price              46436 non-null  float64
 21  Cur_Status              46436 non-null  object
 22  Address_1               46422 non-null  object
 23  Pincode                 46436 non-null  int64
 24  Delivery_State          46435 non-null  object
 25  Location                46436 non-null  object
 26  Marketplace_awb_number  36161 non-null  object
 27  Cust_Name               45535 non-null  object
 28  Mobile                  45535 non-null  object
 29  Store_Code              46436 non-null  object
 30  Cur_Store_Code          46436 non-null  object
 31  Store_Address           46436 non-null  object
 32  Store_City              46436 non-null  object
 33  Store_State             46436 non-null  object
 34  del_cust_name           46436 non-null  object
 35  del_cust_mobile         46436 non-null  object
 36  l1_category             46436 non-null  object
 37  l3_category             46436 non-null  object
 38  Company_Name            46436 non-null  object
 39  hsn_code                46436 non-null  int64
 40  invoice_id              36958 non-null  object
 41  MRP                     46436 non-null  float64
dtypes: float64(7), int64(4), object(30), uint64(1)
memory usage: 14.9+ MB

In [7]:
data.isnull().sum()

date                          0
ordering_channel              0
mode_of_payment               0
bag_id                        0
shipment_id                   0
affiliate_bag_id              0
order_id                      0
Itemcode                      0
sku_code                  16353
ean                       30083
upc                       46436
item_gender               10782
article_qnty                  0
ProdName                      0
Size                       1084
Brand                         0
Gender                    46436
payment_mode                 15
ESP                           0
Amount_Paid                   0
unit_price                    0
Cur_Status                    0
Address_1                    14
Pincode                       0
Delivery_State                1
Location                      0
Marketplace_awb_number    10275
Cust_Name                   901
Mobile                      901
Store_Code                    0
Cur_Store_Code                0
Store_Address                 0
Store_City                    0
Store_State                   0
del_cust_name                 0
del_cust_mobile               0
l1_category                   0
l3_category                   0
Company_Name                  0
hsn_code                      0
invoice_id                 9478
MRP                           0
dtype: int64

In [8]:
data.duplicated().sum()

0